import {
	FOOTER,
	UICONFIG,
	AGEGATE,
	VERIFYAGE,
	GTM_CONTAINERS,
	CHECK_BOX_AGE_GATE,
	META_TAGS,
} from './Global/index';
import { PROMOS, PAGE } from './Promos/index';
import { GOOGLE_MAPS_API, ZONES, USER_LOCATION } from './Location/index';

export const types = {
	FOOTER,
	UICONFIG,
	AGEGATE,
	PROMOS,
	VERIFYAGE,
	PAGE,
	GTM_CONTAINERS,
	GOOGLE_MAPS_API,
	ZONES,
	USER_LOCATION,
	CHECK_BOX_AGE_GATE,
	META_TAGS,
};
